name: CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Run make
      run: make

    - id: create_release
      name: Create new release on GitHub
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: xkcd-term ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binary to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/xkcd
        asset_name: xkcd-linux-amd64-glibc
        asset_content_type: application/octet-stream

    - name: Upload SHA256 to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/xkcd.sha256
        asset_name: xkcd-linux-amd64-glibc.sha256
        asset_content_type: text/plain
